
spring:
  datasource:
    user:
      jdbc-url: jdbc:mysql://${USER_DB_HOST:192.168.0.228}:${USER_DB_PORT:6301}/hwuser?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: ${USER_DB_USER:root}
      password: ${USER_DB_PWD:*df}
      # 初始化连接数
      initial-size: 0
      # 最大连接数
      max-active: 2
      # 最小连接数
      min-idle: 0
      # 获取连接最长等待时间 ms
      max-wait: 30000
    log:
      jdbc-url: jdbc:mysql://${USER_DB_HOST:192.168.0.228}:${USER_DB_PORT:6301}/hwuser?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: ${USER_DB_USER:root}
      password: ${USER_DB_PWD:*df}
      # 初始化连接数
      initial-size: 0
      # 最大连接数
      max-active: 2
      # 最小连接数
      min-idle: 0
      # 获取连接最长等待时间 ms
      max-wait: 30000
